import belt_conveyor

def test_move():
  assert belt_conveyor.move(["RDU", "LRU"], 2, 3) == (1, 3)
  assert belt_conveyor.move(["RRD", "ULL"], 2, 3) == -1
  assert belt_conveyor.move(
    [
      "RRDDDDRRRDDDRRRRRRDDDRDDDDRDDRDDDDDDRRDRRRRR", 
      "RRRDLRDRDLLLLRDRRLLLDDRDLLLRDDDLLLDRRLLLLLDD", 
      "DRDLRLDRDLRDRLDRLRDDLDDLRDRLDRLDDRLRRLRRRDRR", 
      "DDLRRDLDDLDDRLDDLDRDDRDDDDRLRRLRDDRRRLDRDRDD", 
      "RDLRRDLRDLLLLRRDLRDRRDRRRDLRDDLLLLDDDLLLLRDR", 
      "RDLLLLLRDLRDRLDDLDDRDRRDRLDRRRLDDDLDDDRDDLDR", 
      "RDLRRDLDDLRDRLRDLDDDLDDRLDRDRDLDRDLDDLRRDLRR", 
      "RDLDRRLDRLLLLDRDRLLLRDDLLLLLRDRLLLRRRRLLLDDR", 
      "RRRRDRDDRRRDDRDDDRRRDRDRDRDRRRRRRDDDRDDDDRRR"
    ], 9, 44) == (9, 5)






